### ISSUE TITLE
Did 5.3 break Cactbot/Raidboss?

### ISSUE THREAD

**Issue by KingAzi** [quisquous/cactbot#1666]
## Description

Did the 5.3 patch break Cactpot/Raidboss? Or is it just me? 

Description of the issue you're seeing.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by lottiebee** [comment]
Mine is definitely borked, but that is to be expected with a new patch. Here is my issue, hope this helps someone haha

[8/11/2020 8:41:19 PM] Error: Unable to read data file: Could not find file 'C:\Users\X\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot-0.18.0\cactbot\ui\raidboss\data\05-shb\trial\ruby_weapon.js'.
[8/11/2020 8:41:19 PM] Error: Unable to read data file: Could not find file 'C:\Users\X\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot-0.18.0\cactbot\ui\raidboss\data\05-shb\trial\ruby_weapon.txt'.
[8/11/2020 8:41:19 PM] Error: Unable to read data file: Could not find file 'C:\Users\X\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot-0.18.0\cactbot\ui\raidboss\data\05-shb\trial\ruby_weapon-ex.js'.
[8/11/2020 8:41:19 PM] Error: Unable to read data file: Could not find file 'C:\Users\X\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot-0.18.0\cactbot\ui\raidboss\data\05-shb\trial\ruby_weapon-ex.txt'.
[8/11/2020 8:41:19 PM] Info: RaidBoss: BrowserConsole: Error parsing JSON from 05-shb/raid/e2n.js: TypeError: Responses.lookAwayFrom is not a function (Source: file:///C:/Users/X/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.18.0/cactbot/ui/raidboss/popup-text.js, Line: 120)
[8/11/2020 8:41:19 PM] Info: RaidBoss: BrowserConsole: Error parsing JSON from 05-shb/raid/e2s.js: TypeError: Responses.lookAwayFrom is not a function (Source: file:///C:/Users/X/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.18.0/cactbot/ui/raidboss/popup-text.js, Line: 120)
[8/11/2020 8:41:20 PM] Info: RaidBoss: BrowserConsole: Loading 00-misc/general.js (Source: file:///C:/Users/X/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.18.0/cactbot/ui/raidboss/popup-text.js, Line: 222)
[8/11/2020 8:41:22 PM] Info: Found enmity memory for 5.3.

**Comment by quisquous** [comment]
5.3 should be working with the latest.  @lottiebee it sounds like you're missing files due to a messed up update.  I would unclick the "reload overlay on file change" option in cactbot, and then reinstall the latest version of cactbot (or the 0.19.1 update).

**Comment by KingAzi** [comment]
I deleted Cactpot and OverlayPlugin then reinstalled from scratch and it's working again. I think I had the same problem as littiebee.

**Comment by KingAzi** [comment]
Found out the Alerts are still broken. I did a Test Game Connection test and while it shows the location I'm in and finds FF14, it's saying some FFXIV memory signatures aren't detected and that probably means that FFXIV_ACT_Plugin needs an update.

It's not parsing...so I'm guessing it's not Cactpot that's broken but FFXIV_ACT_Plugin

**Comment by quisquous** [comment]
Yes.  There's a beta plugin pinned in [#beta-testing](https://discord.gg/ahFKcmx).

**Comment by lottiebee** [comment]
> 5.3 should be working with the latest. @lottiebee it sounds like you're missing files due to a messed up update. I would unclick the "reload overlay on file change" option in cactbot, and then reinstall the latest version of cactbot (or the 0.19.1 update).

Thanks for the advice! I'll give that a shot! :)

**Comment by lottiebee** [comment]
> Found out the Alerts are still broken. I did a Test Game Connection test and while it shows the location I'm in and finds FF14, it's saying some FFXIV memory signatures aren't detected and that probably means that FFXIV_ACT_Plugin needs an update.
> 
> It's not parsing...so I'm guessing it's not Cactpot that's broken but FFXIV_ACT_Plugin

Yeah I was thinking the same thing last night

**Comment by KingAzi** [comment]
> Yes. There's a beta plugin pinned in [#beta-testing](https://discord.gg/ahFKcmx).

It was the FFXIV_ACT_Plugin after all. I went to the discord you linked and downloaded the pinned beta FFXIV_ACT_Plugin, extracted it, and copied it over the file (replaced the file) with the same name in my AppData folder. Rebooted ACT and everything is working again! If anyone else is having the same problems you can do what I did, or wait on the official FFXIV_ACT_Plugin update to be released.

Thanks Quisquous!!

**Comment by quisquous** [comment]
Sounds good.  I'll go ahead and close this now.
