### ISSUE TITLE
Issue with raidboss and testbars

### ISSUE THREAD

**Issue by michii88** [quisquous/cactbot#28]
gonna shift the conversation over here as you requested. I finally have the test bars visible, however the timelines do not work when i bow. I have tested my text alerts and they work fine. when i go to the timeline plugin I get this error. when i bow to the dummy at summer ford I don't get any timelines.
 
![timeline error](https://user-images.githubusercontent.com/35468030/35010269-f97042c0-fac7-11e7-8a52-924c5d3f3961.png)

**Comment by quisquous** [comment]
Thanks for the screenshot.

So cactbot and raidboss are different things than the ACT Timeline plugin.  If you have raidboss set up through the OverlayPlugin, then that gets you both triggers and timelines.

I've heard of some folks having issues with starting the test timeline.  Do you have emotes turned on? If you /bow to the striking dummy, do you get text in the log that says something like "You bow courteously to the striking dummy?" If no, does the timeline start if you do "/echo You bow courteously to the striking dummy".

I'm going to update this test timeline so that it starts with /countdown in the next release, at the very least.

**Comment by michii88** [comment]
Ive done both and not getting any thing as far as timelines are concerned. i went through rabanastre and the text alerts work but no timelines. 
![poke](https://user-images.githubusercontent.com/35468030/35024128-7528d518-fb03-11e7-9a74-558c64fad876.jpg)
**This is the poke test, works like a charm**

![bow](https://user-images.githubusercontent.com/35468030/35024151-8c472254-fb03-11e7-9fef-7ff40caddb78.jpg)
**This is the /bow and /echo test and nothing. thanks so much for your help.**

**Comment by michii88** [comment]
also this is the view from the overlay plugin.dll. this may be of more assistance. its having a problem finding the timeline files. this may help some other people with this problem 
![timeline error 2](https://user-images.githubusercontent.com/35468030/35024364-abf94400-fb04-11e7-8085-066a4320d735.jpg)

**Comment by quisquous** [comment]
Aha! Thanks for the screenshots.  Those errors look like you're missing the timeline files entirely.

What is in your cactbot/ui/raidboss folder? It looks like you have cactbot/ui/raidboss/data/triggers if that's working, but maybe you're missing cactbot/ui/raidboss/data/timelines?  You definitely have cactbot/ui/raidboss/data/manifest.txt if it's finding the list of filenames.

If you have those files but it's not able to load them, that's also mysterious.  Are you running ACT in administrator mode?

**Comment by quisquous** [comment]
Were you able to solve this issue?

**Comment by michii88** [comment]
Yes, It was resolved. I can explain why or how with pictures when get home,
for others who may have the same problem.

**Comment by 73u38** [comment]
hello i have same problem my dps ui and raidboss ui not working. i tried on striking dummy but not working already try using /bow or countdown and still not working :(

**Comment by 73u38** [comment]
![image](https://user-images.githubusercontent.com/6307962/35691001-f6849446-07a9-11e8-9541-3d1134a5d954.png) this my test result

**Comment by michii88** [comment]
well some preliminary stuff to get out the way, i need to ask some questions. What release are you using, as this was about problems with 5.2. if this is a 6.0 question you will prob do better to start a new thread. secondly if it is the new release, you may want to check to see if you have the most recent act plugin that was recently released.

**Comment by 73u38** [comment]
okay i open new thread

**Comment by michii88** [comment]
@quisquous also the issue that i was having was that I had cactbot installed in 2 different folders in my act folder. so it was having trouble knowing which one to read. ill post pics for future references as I think the operator  error can happen on any release. Also a suggestion, is it possible to clear up where to place the cactbot folder exactly if downloading the whole thing and not making a dll from scratch?

**Comment by quisquous** [comment]
There's a spot in the readme that says something like "the final directory structure should look something like this".  Is there some clearer way to write that section?

**Comment by michii88** [comment]
Ill have to take another look at what i misunderstood when I get home. will let you know

**Comment by quisquous** [comment]
Thanks! I appreciate the help to try to figure out how to make cactbot installation and update clearer.  I've had a bunch of folks tell me that it's been confusing, so any advice or pointers I can add to help future folks would be really great. :)

**Comment by michii88** [comment]
@quisquous so for me the confusion came from verbiage. If you have some people who have never went behind a hood of a program so complex but have some tech knowledge to know that one wrong file can majorly mess up a program (me) things will be taking literal to explain a bit.

![reading4](https://user-images.githubusercontent.com/35468030/35711381-359044e6-0782-11e8-8017-41ddcfb78ec0.PNG)
 
confused me because I wasn't sure if i was to drop my overlay plugin into the overlay plugin folder.

which leads to extra unnecessary paths like such (this was the path i had to take to get it to work

![reading](https://user-images.githubusercontent.com/35468030/35711417-6f8f312a-0782-11e8-8260-acc9f1a4832c.PNG)

I would either word that step as "Copy the OverlayPlugin\ folder from inside of the unzipped folder into your existing C:\...\Advanced Combat Tracker folder and merge it with the existing overlay. 
           

 a. Click yes 
![reading5](https://user-images.githubusercontent.com/35468030/35711664-b8136af0-0783-11e8-820c-ce97ada9dc32.PNG)

b. Then click move and replace and tick box for other conflicts (this will just replace replica files if you have any from older versions)
![reading6](https://user-images.githubusercontent.com/35468030/35711743-0d398cd0-0784-11e8-954f-1e04684dd9ed.PNG)


If this is to much and you want to just refer people to this post that is fine as well.
