### ISSUE TITLE
ngld overlayplugin is crashy

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#660]
See my comments on #577.

Filing this issue just to have a place to have this conversation and for other people to chime in if they're having the same issue.

**Comment by nicholasnjh** [comment]
(1) disable the hibiyasleep OverlayPlugin.dll in ACT, close ACT
(2) download the latest version of the ngld overlayplugin
(3) unblock and unzip that somewhere on disk
(4) load the OverlayPlugin.dll in that folder as an ACT plugin
(5) download the cactbot-0.11.1-ngld.zip file
(6) read and follow these new instructions carefully: https://github.com/quisquous/cactbot/tree/ngldoverlay#installing-cactbot
(7) you will need to re-add all of your overlays, sorry
(8) please also click the "Automatically Report Errors" checkbox in the general tab


I followed the steps, once i disabled hibiyasleep overlayplugin.dll everything stops working, my acts stops responding altogether. nvm , i force closed it, reopened it and loaded the new overlayplugin and it prompted with

"Could not load type 'rainbowmage.overlayplugin.registry' from assembly 'overlayplugin.common, version= 0.3.4.0. culture= netral, publickeytoken = null

**Comment by nicholasnjh** [comment]
wait.. where is the timeline for it now? it doesnt show it anymore... or I cant browse to add in cactbot overlay helpppppppppppppppppppppppppppppppppppp
![image](https://user-images.githubusercontent.com/40110522/66763362-4df9ab80-eeda-11e9-9af6-ec3885d12763.png)

**Comment by Akurosia** [comment]
Just tried to use ngld's version, but as soon as i add the raidboss overlay, i get following log output

> [14.10.2019 17:57:55] Info: InitPlugin: PluginDirectory = E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld
[14.10.2019 17:57:56] Info: InitPlugin: Initialized.
[14.10.2019 17:57:56] Error: Got a subscription for missing event "onPlayerChangedEvent"!
[14.10.2019 17:57:56] Error: Got a subscription for missing event "onLogEvent"!
[14.10.2019 17:57:56] Error: Got a subscription for missing event "onGameActiveChangedEvent"!
[14.10.2019 17:57:56] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotReadDataFiles"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass15_0.<callHandler>b__0()
[14.10.2019 17:57:56] Error: Got a subscription for missing event "onZoneChangedEvent"!
[14.10.2019 17:57:56] Error: Got a subscription for missing event "onInCombatChangedEvent"!
[14.10.2019 17:57:56] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass15_0.<callHandler>b__0()

So far also nothing worked for me (tried redownloading both nglds overlay plugin + cactbot version, unblock it, also other cactbot overlay throw similar issues)

**Comment by ngld** [comment]
```
"Could not load type 'rainbowmage.overlayplugin.registry' from assembly 'overlayplugin.common, version= 0.3.4.0. culture= netral, publickeytoken = null
```
That error means that the old OverlayPlugin is still loaded, either because ACT hasn't been restarted after disabling the old plugin or because the old DLLs are in the wrong folder (like the ACT folder).

@Akurosia After adding Cactbot, restart ACT. Does that fix the issue?

**Comment by quisquous** [comment]
@Akurosia I think @panicstevenson reported this same issue and said that a restart fixed it.

**Comment by panicstevenson** [comment]
I figured my experience was going to be unique, but just in case anyone else does the same: I did everything in place. I put everything in their old folders, overwriting DLLs, etc. as necessary. I would not recommend this approach.

I actually had to restart ACT twice; initially, everything was erroring in a very obvious and obnoxious manner. Upon coming back up, everything looked great and then I was met with Cactbot errors. Probably not the most obvious thing since everything just came up fresh, I restarted ACT _again_ and then everything went away; no configuration change on my end.

**Comment by Akurosia** [comment]
I retsarted multiple times and stil could reproduce this on my end.
Also i tested if the hibiya version was working still and tried it again with multiple restarts in between but still no luck for my side.
I will try it again later today after cleaning the config file for the overlayplugin(ngld) to see if it was just the config that got currupted.

**Comment by ngld** [comment]
Weird. You did add CactbotOverlay.dll as a plugin, right? What's ACT displaying as the status (the field below the plugin name)?

**Comment by Akurosia** [comment]
@ngld 
here a small status update:
Order of Plugins: FFXIV_ACT, OverlayPlugin, Cactbot
Status of OverlayPlugin: Initialized
Status of Cactbot: Ready

I cleared now all OverlayPlugin (ngld) related files and tried everything again (always with small different kind of errors) but after like the 6th try or so it worked (always made sure to restart multiple times to test if this helped, but apparently it didn't work for me).
What i noticed is, that i did not had either the CactbotEventSource element or the MiniParseEventSource available. Now, as i have both available, it works.

What my tests showed, is that i can remove the CactbotEventSource element while i can't remove the MiniParseEventSource element manually.

**Comment by ngld** [comment]
The errors you saw occured since the CactbotEventSource wasn't registered in OverlayPlugin (it provides the missing events and handlers).
Removing CactbotEventSource in the UI doesn't actually do anything (except hide the tab). It's more of an oversight that you can actually close that tab... you're not even supposed to be able to do that.

Now I'm curious what changed between the restarts and why OverlayPlugin didn't detect Cactbot before...

**Comment by ngld** [comment]
The problem with addon detection is that at the time OverlayPlugin is initialized through ACT, only the plugins listed above it have been loaded and the remaining plugins aren't accessible since it's still parsing the XML configuration at that point.
To find addons that are listed after OverlayPlugin, it waits for the main window to become visible which should only happen after it's done loading all plugins. The only explanation why Cactbot isn't detected during ACT startup but loads fine if OverlayPlugin is enabled afterwards seems to be that the main window is visible before Cactbot is loaded. I wonder why that would happen...

Do you use any other plugins? Which ACT version do you use?
Finally, as a workaround, you can still put the `CactbotOverlay.dll` file in OverlayPlugin's `addons` folder.

**Comment by nicholasnjh** [comment]
![image](https://user-images.githubusercontent.com/40110522/66945169-298c0380-f081-11e9-9a03-9027c5ba2f98.png)
![image](https://user-images.githubusercontent.com/40110522/66945254-4cb6b300-f081-11e9-8ccb-0e0664692623.png)

Ive had time to time freeze / staggers for like a second, and soemtimes the timelines jsut never appear at all . sometimes they do

**Comment by ngld** [comment]
Not sure about the freezes but the console errors would cause issues with timelines. That's another race condition during overlay load but it should be easy to fix.

**Comment by eestyle** [comment]
ACT version 3.4.4.264
I use special spell timer, and a chat translate plugin as well as Mopi Mopi with websocket just so I can record game play with parses on window capture.

**Comment by nicholasnjh** [comment]
I would like to leave another comment on the problem, The timelines work fine, and then suddenly they just disappear for no apparent reason throughout the rest of the fight , this was in a dungeon when i was running ( the twinning) boss had timeline, then suddenly it just went off , like on the last 30% or something

**Comment by ngld** [comment]
Did you see any errors in the log (the text box below the overlay settings)?

**Comment by nicholasnjh** [comment]
> Did you see any errors in the log (the text box below the overlay settings)?

![image](https://user-images.githubusercontent.com/40110522/67136318-598cff80-f257-11e9-81be-ccfb079136ea.png)

**Comment by ngld** [comment]
Sorry, forgot that the fix hasn't made it into a release, yet. Can you test if https://rawcdn.githack.com/quisquous/cactbot/bb048b268dcc556d1579129e7a34547fae786de1/ui/raidboss/raidboss.html fixes your problems?

**Comment by ngld** [comment]
@eestyle @Akurosia  If you place `CactbotOverlay.dll` in OverlayPlugin's addons folder (and don't add it to ACT as a plugin), does that resolve your startup issues?

**Comment by nicholasnjh** [comment]
> Sorry, forgot that the fix hasn't made it into a release, yet. Can you test if https://rawcdn.githack.com/quisquous/cactbot/bb048b268dcc556d1579129e7a34547fae786de1/ui/raidboss/raidboss.html fixes your problems?

its a blank page when i tried to open it , or you telling me to use that link as the URL in the cactbot URL bit?

**Comment by ngld** [comment]
Yes. Load that instead of your local `raidboss.html` in your overlay.

**Comment by eestyle** [comment]
@ngld Yes it does solve it, though however it showed some other errors during start up, but it will load properly. Heres the logs

[20/10/2019 10:29:07 AM] Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\Plugins\NGLD Overlay
[20/10/2019 10:29:07 AM] Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\Plugins\NGLD Overlay\addons\CactbotOverlay.dll
[20/10/2019 10:29:07 AM] Info: LoadAddons: Cactbot.PluginLoader: Initialized
[20/10/2019 10:29:07 AM] Error: LoadAddons: Cactbot.OverlayAddonMain: RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> System.Exception: Duplicate handler for name cactbotLoadUser!
   at RainbowMage.OverlayPlugin.EventDispatcher.RegisterHandler(String name, Func`2 handler)
   at Cactbot.CactbotEventSource..ctor(ILogger logger)
   at lambda_method(Closure , Object[] )
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.Registry.RegisterEventSource[T]()
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
[20/10/2019 10:29:09 AM] Info: cactbot: 0.11.1.0 C:\Program Files (x86)\Advanced Combat Tracker\Plugins\NGLD Overlay\addons\CactbotOverlay.dll
[20/10/2019 10:29:09 AM] Info: OverlayPlugin: 0.7.2.0 
[20/10/2019 10:29:09 AM] Info: FFXIV Plugin: 2.0.4.0 
[20/10/2019 10:29:09 AM] Info: ACT: 3.4.4.264 C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe
[20/10/2019 10:29:09 AM] Info: Language: en
[20/10/2019 10:29:09 AM] Info: InitPlugin: Initialized.

I haven't updated to 0.8.1 though.

**Comment by ngld** [comment]
> Duplicate handler for name cactbotLoadUser!

Now it's being loaded twice... Once you remove `CactbotOverlay.dll` from your plugins list in ACT, the issue should be resolved.

**Comment by eestyle** [comment]
Actually I have already removed the cactbotoverlay.dll from plugins list and even tried deleting the file from the cactbot folder so that its only in the ngld overlay addons folder. Its still showing the same error. Perhaps there are something wrong with my ACT config files or something.

**Comment by ngld** [comment]
Hmm... no. I think there's an old file still left in this Cactbot build. Can you replace your `CactbotOverlay.dll` with [this one](https://github.com/quisquous/cactbot/files/3747945/CactbotOverlay.zip) and see if that changes anything?

**Comment by eestyle** [comment]
The new file loaded without any errors if added in overlay addon folder. Though if I use it under plugin listing I still get the subscription for missing event error. Thank you for this, I will just use it in the addons for now.

**Comment by Akurosia** [comment]
@ngld with the latest cactbot release 0.11.2 and your latest overlay plugin 0.8.1 and with the previously mentioned CactbotOverlay.dll inside the addon folder i get following log:
NOTE: this also happens without the previously mentioned CactbotOverlay.dll

> [22.10.2019 17:51:03] Info: InitPlugin: PluginDirectory = E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld
[22.10.2019 17:51:03] Info: LoadAddons: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\addons\CactbotOverlay.dll
[22.10.2019 17:51:03] Error: LoadAddons: Cactbot.PluginLoader: RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> System.MissingMethodException: Methode nicht gefunden: "Void RainbowMage.OverlayPlugin.EventSourceBase.RegisterEventHandler(System.String, System.Func`2<Newtonsoft.Json.Linq.JObject,Newtonsoft.Json.Linq.JToken>)".
   bei Cactbot.CactbotEventSource..ctor(ILogger logger)
   bei lambda_method(Closure , Object[] )
   bei RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   bei RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   bei RainbowMage.OverlayPlugin.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   bei RainbowMage.OverlayPlugin.Registry.RegisterEventSource[T]()
   bei RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
[22.10.2019 17:51:04] Info: InitPlugin: Initialized.
[22.10.2019 17:51:05] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 17:51:05] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 17:51:05] Error: Got a subscription for missing event "onPlayerChangedEvent"!
[22.10.2019 17:51:06] Error: Got a subscription for missing event "onPlayerChangedEvent"!
[22.10.2019 17:51:06] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 17:51:06] Error: Got a subscription for missing event "onImportLogEvent"!
[22.10.2019 17:51:06] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 17:51:06] Error: JS Handler call failed: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 22.
   bei Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   bei Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 17:51:06] Error: Got a subscription for missing event "onPlayerChangedEvent"!
[22.10.2019 17:51:06] Error: Got a subscription for missing event "onPlayerChangedEvent"!
[22.10.2019 17:51:06] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 17:51:06] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()

**Comment by ngld** [comment]
Can you check if you have a `Newtonsoft.Json.dll` file in your ACT folder? In OverlayPlugin's folder, the only DLL is `OverlayPlugin.dll` and all other DLLs are in the `libs` subfolder, right?
Finally, can you try disabling all plugins except the FFXIV plugin and OverlayPlugin then restarting ACT?

**Comment by Akurosia** [comment]
I dont have the `Newtonsoft.Json.dll` either in ACT nor in my `OverlayPlugin_ngld` folder (but its inside my `OverlayPlugin_ngld/libs/` folder)

I disabled all my plugins except the FFXIV_ACT_Plugin.dll and the OverlayPlugin_ngld\OverlayPlugin.dll

I get now following error:

> [22.10.2019 18:09:44] Info: InitPlugin: PluginDirectory = E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld
[22.10.2019 18:09:44] Info: LoadAddons: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\addons\CactbotOverlay.dll
[22.10.2019 18:09:44] Error: LoadAddons: Cactbot.PluginLoader: RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> System.MissingMethodException: Methode nicht gefunden: "Void RainbowMage.OverlayPlugin.EventSourceBase.RegisterEventHandler(System.String, System.Func`2<Newtonsoft.Json.Linq.JObject,Newtonsoft.Json.Linq.JToken>)".
   bei Cactbot.CactbotEventSource..ctor(ILogger logger)
   bei lambda_method(Closure , Object[] )
   bei RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   bei RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   bei RainbowMage.OverlayPlugin.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   bei RainbowMage.OverlayPlugin.Registry.RegisterEventSource[T]()
   bei RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
[22.10.2019 18:09:45] Info: InitPlugin: Initialized.
[22.10.2019 18:09:45] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 18:09:45] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 18:09:45] Error: Got a subscription for missing event "onPlayerChangedEvent"!
[22.10.2019 18:09:46] Error: Got a subscription for missing event "onPlayerChangedEvent"!
[22.10.2019 18:09:46] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 18:09:46] Error: Got a subscription for missing event "onImportLogEvent"!
[22.10.2019 18:09:46] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 18:09:46] Error: JS Handler call failed: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 22.
   bei Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   bei Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 18:09:46] Error: Got a subscription for missing event "onPlayerChangedEvent"!
[22.10.2019 18:09:46] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
[22.10.2019 18:09:46] Error: Got a subscription for missing event "onPlayerChangedEvent"!
[22.10.2019 18:09:46] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   bei RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()

**Comment by ngld** [comment]
So it's still the same error. Hm... I last touched the method it's complaining about 2 months ago so I doubt that's the actual issue here (unless you have a very old version of OverlayPlugin).
Can you double check? If you select OverlayPlugin in the plugins list, it should display 0.8.1.0 as the version on the right side.

The only other possible cause for that error is that .NET managed to load two copies of `Newtonsoft.Json.dll` but if that's happening I'm wondering why it worked for the other person before.

**Comment by Akurosia** [comment]
This is th eoutput from your plugin version (i espacilly made 2 directions so i can swap in case of an error between your version and hibiya without compromising either the hibiya or your version):

> Assembly Info:
FileName: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\OverlayPlugin.dll
OriginalFilename: OverlayPlugin.dll
FileVersion: 0.8.1.0
ProductVersion: 0.8.1.0
FileDescription: OverlayPlugin
ProductName: OverlayPlugin
LegalCopyright: Copyright © RainbowMage 2015, Kuriyama hibiya 2016, ngld 2019
Comments: Overlay plugin for Advanced Combat Tracker

**Comment by ngld** [comment]
The hibiya files are in a subfolder and not in ACT's own folder, right? Can you attach your `OverlayPlugin.Core.dll` file? Should be in `OverlayPlugin_ngld\libs` and you might have to put it in a `.zip` to upload it (GitHub checks file extensions).

**Comment by Akurosia** [comment]
All my plugins are always in `ACT/Plugins/NAMEOFPLUGIN/` e.g. your plugin is in `ACT\Plugins\OverlayPlugin_ngld` while hibiya is in `ACT\Plugins\OverlayPlugin_hibiya` where the only exception is the FFXIV_ACT_Plugin itself which lies in  `ACT/Plugins/` directly
Also here the requested OverlayPlugin.Core.dll : [OverlayPlugin.Core.zip](https://github.com/quisquous/cactbot/files/3757173/OverlayPlugin.Core.zip)

**Comment by ngld** [comment]
So... that DLL includes the method that the error is complaining about and it *is* loaded since that file contains the logic to load addons. AFAIK that only leaves the possibility that Newtonsoft.Json.dll is loaded twice which seems pretty weird given what you've said before.

**Comment by Akurosia** [comment]
From the ACT config, these are my plugins for the test i ran while testing your version:

```    
    <ActPlugins>
        <Plugin Enabled="False" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\websoket\ACTWebSocket.dll" />
        <Plugin Enabled="True" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\FFXIV_ACT_Plugin.dll" />
        <Plugin Enabled="False" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_hibiya\OverlayPlugin.dll" />
        <Plugin Enabled="True" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\OverlayPlugin.dll" />
        <Plugin Enabled="False" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\Triggernometry\Triggernometry.dll" />
        <Plugin Enabled="False" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\ping\ACT.FFXIVPing.dll" />
        <Plugin Enabled="False" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\SlimDX_XAudio\SlimDX_XAudio2.dll" />
        <Plugin Enabled="False" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\Hojuring\ACT.TTSYukkuri.dll" />
        <Plugin Enabled="False" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\Hojuring\ACT.UltraScouter.dll" />
        <Plugin Enabled="False" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\Hojuring\ACT.SpecialSpellTimer.dll" />
        <Plugin Enabled="False" Path="E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\Universalis\UniversalisPlugin.dll" />
    </ActPlugins>
```

**Comment by Akurosia** [comment]
I think i found the culprit...
I have a 4k and a 3440x1440 display, so i had a lot of problems with ACT rescalling to a tiny size whenever it started on my 4k display.
So i activated the windows internal HighDPI scalling feature (Rightclick on the `Advanced Combat Tracker.exe` > `Compatibility` tab > `Change High DPI Settings`) There i activated the Second checkbox and set it to application
Apparently it seams, whenever i do this, i have the cactbot loading issue. If i remove it, ACT is loading everything fine (except its actual size in generall as it is way to tiny)

**Comment by eestyle** [comment]
Can confirm, also on dual monitor, after unchecking hogh dpi scalling it will load the plugin normally. Though I still cannot get raidboss to work properly. No error messages but raidboss would not start when I test it in summarford farm. Test plugin shows its detecting everything though. After reverting back to hibi plugin I now get an error on raidboss.html line 66 and 63 which dosent exist...though the plugin works with those errors. Tried fresh install  act with the same result from new and old overlay plugin.

**Comment by geetarkev** [comment]
Attempted changing overlay plugin to ngld yesterday. Things went bad. Ended up doing a fresh ACT install and now I'm getting this error whether I use hibiyasleep or ngld:

Info: Cactbot: BrowserConsole: Unknown job role (Source: file:///C:/Users/geeta/cactbot/resources/common.js, Line: 35)

The Test html works fine, but some of the others do not, including raidboss.

**Comment by ngld** [comment]
The 5.1 patch broke the FFXIV plugin. We'll have to wait until that's updated before ACT is usable again.

**Comment by geetarkev** [comment]
Ah, that's good to hear. I thought I was being an idiot again today.

**Comment by geetarkev** [comment]
I'm getting this error even after doing a complete fresh install:

Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()

**Comment by ngld** [comment]
That means that the Cactbot addon hasn't been loaded. Make sure that the Cactbot EventSource appears in the overlay list:
![Advanced_Combat_Tracker_2019-10-31_07-52-54](https://user-images.githubusercontent.com/5465775/67925399-86c0a280-fbb3-11e9-9898-719469204251.png)

If Cactbot is in the plugins list and enabled but still doesn't appear in OverlayPlugin, try moving the `CactbotOverlay.dll` in OverlayPlugin's `addons` folder and restart ACT.

**Comment by de-gene-rate** [comment]
Can also confirm that the plugin is not friendly with the windows DPI compatibility settings. For the life of me no matter what I did the log would keep spitting errors and the timeline wouldnt load at all in game.

Read that turning off DPI compatibility worked for a couple of people and that did it. Everything looks fine now. 

Also if you need to do this, you can increase the ACT window text by going to the ACT Options tab -> Color and Font Settings -> Main User Interface -> click each of the 3 Change Font buttons one by one and increase their size till you get something that works for you.

**Comment by geetarkev** [comment]
Unfortunately putting it in addons leaves me with a string of even more errors.

Error: LoadAddons: Cactbot.PluginLoader: RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> System.MissingMethodException: Method not found: 'Void RainbowMage.OverlayPlugin.EventSourceBase.RegisterEventHandler(System.String, System.Func`2<Newtonsoft.Json.Linq.JObject,Newtonsoft.Json.Linq.JToken>)'.
   at Cactbot.CactbotEventSource..ctor(ILogger logger)
   at lambda_method(Closure , Object[] )
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.Registry.RegisterEventSource[T]()
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
[10/31/2019 10:44:17 AM] Error: LoadAddons: Cactbot.OverlayAddonMain: RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> System.MissingMethodException: Method not found: 'Void RainbowMage.OverlayPlugin.EventSourceBase.RegisterEventHandler(System.String, System.Func`2<Newtonsoft.Json.Linq.JObject,Newtonsoft.Json.Linq.JToken>)'.
   at Cactbot.CactbotEventSource..ctor(ILogger logger)
   at lambda_method(Closure , Object[] )
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.Registry.RegisterEventSource[T]()
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
[10/31/2019 10:44:18 AM] Info: InitPlugin: Initialized.
[10/31/2019 10:44:18 AM] Error: Got a subscription for missing event "onPlayerChangedEvent"!
[10/31/2019 10:44:18 AM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()

**Comment by ngld** [comment]
@geetarkev Have you tried disabling the high DPI compatibility setting as suggested before?

**Comment by geetarkev** [comment]
Okay so that fixed it, thank you! However, I had the dpi settings on because the plugin was screwing with the ACT text and it makes the cactbot timers/alerts smaller.

![act](https://user-images.githubusercontent.com/17958148/67978353-f0f33a80-fbe7-11e9-8dda-1d8d34f9ddc7.png)

**Comment by ngld** [comment]
The weird thing is that I can't reproduce the issue on my own system. No matter what I set my DPI settings to, it works fine (even with the released versions).

I might have found a solution. Can someone with the problem here test [this OverlayPlugin build](https://github.com/quisquous/cactbot/files/3795641/OverlayPlugin-0.9.0.zip)? If that alone doesn't fix it, try moving Cactbot out of the addons folder and add it again as an ACT plugin.

**Comment by geetarkev** [comment]
I'm running a 1440p monitor with windows at 150% scaling otherwise stuff is too small. When I change it to 100% scaling it fixes ACT.

**Comment by Akurosia** [comment]
@ngld After multiple restarts with my previously mentioned highDPI settings, it works at least for me with you just mentioned build (cactbot loaded as dll, not via addon folder).

But i noticed that for some odd reason the jobs overlay does not pick up the jobs.css from my set user directory (which is set to `file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/user`) but does pick up my raidboss.css

Another addition is, when loading the raidboss-emulator an error is always printed when starting ACT or reloading the overlay
```
[31.10.2019 21:19:03] Error: JS Handler call failed: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 22.
   bei Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   bei Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   bei RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
```
>

**Comment by ngld** [comment]
Due to the way ACT loads plugins, Cactbot sometimes fails to detect the user directory. Does it work if you manually select it on the Cactbot EventSource tab?

Regarding the raidboss-emulator issue: That looks like the emulator is sending invalid data to OverlayPlugin. I'll look into it.

**Comment by Akurosia** [comment]
Sry for not beeing clear enough, the path is already manually set to the one i specified above.
Ok now also my raidboss.css/js is not longer working it seams :x

**Comment by ngld** [comment]
Argh, sorry. Read too quickly. If you enable the "Reload overlay on file change" option in the Cactbot tab, it should show a log message like this:
`Info: Started watching C:\...`

Does that mention your user directory or some other path?

**Comment by Akurosia** [comment]
it shows: `[31.10.2019 21:36:23] Info: Started watching E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\../cactbot/user/`

**Comment by Akurosia** [comment]
Ok after enabling the option, closeing and reopening ACT still shows the message in the log BUT inside the actual input-box it only shows `file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/` and when closing ACT a second time, it saves the wrong path

**Comment by ngld** [comment]
I think someone reported that moving the `user` folder to a shorter path and manually selecting that fixed the issue. Not sure if it's about path length or if it's an issue that the `user` folder is in the default location.

**Comment by Akurosia** [comment]
What i think is strange is, that it does not just take the path i specified (which would be `E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\`) but instead it does `E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\../cactbot/user/` so adding the `../cactbot/` stuff inbetween,This is also where the path gets cut-off.

**Comment by ngld** [comment]
The `../cactbot/user` part comes from the auto detection. It takes the path to the DLL and then appends that part.
Regarding the cut off path: What happens if you enter the path with a slash at the end? (i.e. `file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/user/`)

**Comment by Akurosia** [comment]
Seams to fix it (from the short testing i did)

**Comment by ngld** [comment]
There's some weird logic on the settings page that seems to mangle the user directory and using a slash at the end works around that.

@quisquous I'm talking about [this part](https://github.com/quisquous/cactbot/blob/ngldoverlay/CactbotOverlay/CactbotEventSourceConfigPanel.cs#L51). Shouldn't that be `path.LocalPath` instead of `path.AbsolutePath`?

**Comment by geetarkev** [comment]
> The weird thing is that I can't reproduce the issue on my own system. No matter what I set my DPI settings to, it works fine (even with the released versions).
> 
> I might have found a solution. Can someone with the problem here test [this OverlayPlugin build](https://github.com/quisquous/cactbot/files/3795641/OverlayPlugin-0.9.0.zip)? If that alone doesn't fix it, try moving Cactbot out of the addons folder and add it again as an ACT plugin.

Neither of those helped with the text scaling issue.

**Comment by ngld** [comment]
With that build you can reenable the high DPI setting which should fix the text scaling. You might have to set it to "System (Enhanced)" to work properly.

**Comment by geetarkev** [comment]
Okay turning the DPI setting back on fixed it and now ACT looks normal as well as the size of the timers/alerts. Thanks!!!

**Comment by eestyle** [comment]
I finally got everything to work normally with the 9.0 overlay and latest cactbot. Though I havent try turning back dpi scalling. Theres one problem though when I have raidboss.js file in the user folder the raidboss plugin stops working without any errors. If I unlock the overlay it will load multiple timelines non stop while the alert text are normal the computer also freezes from time to time when this happenes. If I put only the raidboss.css file in the user folder and the raidboss.js file in the ui/raidboss folder everything works normally.

**Comment by ngld** [comment]
The load fixes are included in the OverlayPlugin 0.9.1 release so the build linked above should no longer be necessary.

@eestyle Can you try if the same happens with an empty `raidboss.js` file in your `user` folder?

**Comment by eestyle** [comment]
@ngld with an empty raidboss.js file everything works fine. Had to test this with 0.9.1 though since 0.9.0 gives me a rainbowmage error when I launch act and it will force close. Also tried manually assign custom config path in cactbot ebent source tab with no success, as long as there is a raidboss.js file even with basic settings in the user folder this happenes. Have also tried having the raidboss.js file within user folder and remove the one in ui/raidboss folder, but then raidboss stop functioning all together, unlocking overlay shows only text with no timeline.

**Comment by ngld** [comment]
I think this is an issue with your settings since the empty file works fine. Can you post your `raidboss.js` file as a gist or on pastebin? Might help figuring this out.

**Comment by de-gene-rate** [comment]
0.9.0 also just gave me a rainbowmage error when restarting ACT just now. Nothing has changed on my end so I can only assume that the update notification for 0.9.1 is causing the plugin to crash. I installed 0.9.1 and everything seems fine now for anyone who gets a similar error.

**Comment by ngld** [comment]
> Sometimes the update prompt failed with an exception due to being executed on the wrong thread. This has been resolved.

Sounds [like this error](https://cdn.discordapp.com/attachments/551892582855344128/639413211548090388/unknown.png) that the update fixed.

**Comment by eestyle** [comment]
@ngld [https://gist.github.com/eestyle/826583b3c33304fb08e063f97e8b81d0](url)
I actually only changed the display text times and the infotext volume. IIRC I also tested with original raidboss.js file from downloads and the same thing happened.

**Comment by quisquous** [comment]
> @quisquous I'm talking about this part. Shouldn't that be path.LocalPath instead of path.AbsolutePath?

Fixed in 2012d17a51f26790a974fb12a1545b9d96b9b4a4, thanks.

**Comment by quisquous** [comment]
I think this issue has gotten a little bit off track.  I'm going to close it, and folks can open new separate issues if they have them.
